#!/usr/bin/env bash

# get bash colors and styles here: 
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

function __run() #(step, name, cmd)
{
    for FILE in $STAGED_FILES
        do
        ./vendor/bin/phpcs --standard="$RULESET" "$FILE"

        if [[ "$?" == 0 ]]; then
            echo "\t\033[32mPHPCS Passed: $FILE\033[0m"
        else
            echo "\t\033[41mPHPCS Failed: $FILE\033[0m"
            PASS=false
        fi
    done

    echo "\nPHPCS validation completed!\n"

    if ! $PASS; then
        echo -e "${C_RED}\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again.\n"
        exit 1
    else
        echo "COMMIT SUCCEEDED\n"
    fi
}


__run 