#!/usr/bin/env bash

# get bash colors and styles here: 
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_ENDCOLOR='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

RULESET=./phpcs.xml

function runFixer()
{
    for FILE in $STAGED_FILES
        do
        ./vendor/bin/phpcbf --standard="$RULESET" "$FILE"
    done
}

function runSniffer() 
{
    for FILE in $STAGED_FILES
        do
        ./vendor/bin/phpcs --standard="$RULESET" "$FILE"

        if [[ "$?" != 0 ]]; then
           PASS=false
        fi
    done

    echo -e "${C_YELLOW}PHPCS validation completed!${C_ENDCOLOR}"

    if ! $PASS; then
        echo -e "${C_RED}COMMIT FAILED:${C_ENDCOLOR} Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again."
        echo -e "${C_YELLOW} FIXING...${C_ENDCOLOR}"
        runFixer
        exit 1
    else
        echo -e "${C_GREEN}COMMIT SUCCEEDED${C_ENDCOLOR}"
    fi
}




runSniffer 