#!/usr/bin/env bash

# get bash colors and styles here: 
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_YELLOW='\e[33m'

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

RULESET=./phpcs.xml

./vendor/bin/phpcbf --standard="$RULESET" $STAGED_FILES
./vendor/bin/phpcs --standard="$RULESET" $STAGED_FILES

echo -e "${C_YELLOW}PHPCS validation completed!${C_ENDCOLOR}"